server:
  host: "0.0.0.0"
  port: 3000
  timeout_seconds: 30

metrics:
  enabled: true
  port: 9090

tracing:
  enabled: true
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "project-gateway"

mirror:
  enabled: false
  base_url: "http://localhost:4000"
  timeout_ms: 5000
  retry_failed: true
  max_retries: 1

canary_rollout:
  enabled: true
  rollout_percentage: 100
  step: 5
  max_errors: 0.5
  monitor_latency_p99: true
  monitor_memory_cpu: true
  trigger_header: "X-Gateway-Version"
  success_window_seconds: 300
  legacy_gateway_url: "http://localhost:8080"
  webhook_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"

routes:
  # Legacy API routes - to be mirrored exactly
  - path: "/api/v1/health"
    method: "GET"
    legacy_endpoint: "http://localhost:8080/api/v1/health"
  - path: "/api/v1/users"
    method: "GET"
    legacy_endpoint: "http://localhost:8080/api/v1/users"
  - path: "/api/v1/users"
    method: "POST"
    legacy_endpoint: "http://localhost:8080/api/v1/users"ost:8080"
    timeout_ms: 15000

middleware:
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
  
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    
  auth:
    enabled: true
    jwt_secret: "your-secret-key-here"
    
  logging:
    enabled: true
    include_request_body: false
    include_response_body: false

# Modified at Thu Jul  3 01:54:27 EDT 2025
